config/routes.rb
Rails.application.routes.draw do

  namespace :configuration do
    root 'landing#index'
    resources :sections
  end

  post 'login' => 'login#create'

  get 'login' => 'login#index'
  get 'get_reservation_api' => 'reservations#get_reservation_api'
  get 'signup' => 'signup#index'
  post 'signup' => 'signup#create'

  root 'landing#index'
  resources :tables, :reservations

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :table
  belongs_to :user
  validates :table_id, :presence => true
  validates :user_id, :presence => true
  validate :start_time_is_in_the_future,
      :end_time_after_start_time,
      :table_is_not_occupied

  def start_time_is_in_the_future
    errors.add(:start_time, 'Start time should be in the future') if
        DateTime.now >= start_time
  end

  def end_time_after_start_time
    errors.add(:end_time, 'End time should be bigger then start time') if
        start_time >= end_time
  end

  def table_is_not_occupied
    errors.add(:occupied, 'The table is occupied') if
        Reservation.where("table_id = :table_id AND NOT (end_time <= :start_time AND end_time < :end_time OR start_time >= :end_time AND start_time > :start_time)",
                          {start_time: start_time, end_time: end_time, table_id: table_id}).count > 0
  end
end

app/models/table.rb
class Table < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(:id => session[:user_id])
  end

  def logged_in?
    current_user != nil
  end
end

app/controllers/configuration/landing_controller.rb
class Configuration::LandingController < ApplicationController
  def index
  end
end

app/controllers/configuration/sections_controller.rb
class Configuration::SectionsController < ApplicationController
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def create
    if user = User.find_by(:username => params[:username]).try(:authenticate , params[:password])
      session[:user_id] = user.id if user.id
      redirect_to root_url, :notice => 'You have been successfully logged in!!!'
    else
      redirect_to root_url, :alert => 'Your username or password is wrong. Try again!!!'
    end
  end

  def index
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @tables = Table.all
  end

  def create
    startTime = DateTime.parse(params[:date].to_s + 'T' + params[:start_time].to_s + ':00')
    endTime = DateTime.parse(params[:date].to_s + 'T' + params[:end_time].to_s + ':00')

    puts startTime
    puts endTime
    puts params

    reservation = Reservation.new(
        :table_id => params[:table_id],
        :user_id => session[:user_id],
        :start_time => startTime,
        :end_time => endTime
    )
    reservation.save
    redirect_to url_for ({:action => 'index', :controller => 'reservations'})
  end

  def index
    @reservations = Reservation.where('user_id = :user_id AND start_time > :date_now',
                                      {user_id: session[:user_id], date_now: DateTime.now})
  end

  def destroy
    Reservation.find(params[:id]).destroy()
    redirect_to reservations_url
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index

  end

  def create
    if params[:password].eql? params[:passwordConfirmation]
puts params
      user = User.create(:username => params[:username], :password => params[:password])
      if user && user.id
        session[:current_user] = user.id
        redirect_to root_url, :notice => 'You have been redirected!!!'
      else
        redirect_to root_url, :alert => 'This username is occupied!!!'
      end
    else
      redirect_to root_url, :alert => 'Your passwords are different!!!'
    end
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @tables = Table.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/configuration/landing_helper.rb
module Configuration::LandingHelper
end

app/helpers/configuration/sections_helper.rb
module Configuration::SectionsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/configuration/landing/index.html.erb
<h1>Configuration::Landing#index</h1>
<p>Find me in app/views/configuration/landing/index.html.erb</p>

app/views/landing/index.html.erb
<% if flash %>
    <%= debug flash %>
<!--<#% flash[:flashes].each do |msg| -%>
        <#%= msg.inspect %>
    <#%= content_tag :div, msg, :class, 'alert alert-info' %>
<#% end %>-->
    <% end %>

<!--<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Box</title>
  <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand disabled" href="<%= url_for tables_path %>">Tables</a>
      <% if session[:user_id] %>
          <a class="navbar-brand disabled" href="<%= url_for reservations_path %>">Reservations</a>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in? %>
          <form class="navbar-form navbar-right" method="get" action="<%= login_url %>">
            <div class="form-group">
              <span class="label label-default">Welcome, <%= current_user.username %></span>
              <button type="submit" class="btn btn-default">Log out</button>
            </div>
          </form>
      <% else %>
          <form class="navbar-form navbar-right" method="get" action="<%= signup_url %>">
            <div class="form-group">
              <button type="submit" class="btn btn-default">Sign UP</button>
            </div>
          </form>
          <%= form_tag(login_url, :class => 'navbar-form navbar-right', :role => 'login', :method => :post) do %>
              <div class="form-group">
                <input type="text" class="form-control" name="username" placeholder="login">
                <input type="password" class="form-control" name="password" placeholder="password">
              </div>
              <button type="submit" class="btn btn-default">Login</button>
          <% end %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>

</body>
</html>

app/views/reservations/index.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>Table name</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Links</th>
  </tr>
  </thead>
  <tbody>
  <% @reservations.each do |reserv| %>
      <tr scope="row">
        <th><%= reserv.id %></th>
        <td><%= reserv.table.name %></td>
        <td><%= reserv.start_time %></td>
        <td><%= reserv.end_time %></td>
        <td><% if session[:user_id] == reserv.user.id%><%= link_to 'Delete reservation', reserv,  method: :delete,
                                                                   data: { confirm: 'Are you sure?' } %><% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<%= form_tag :reservations, :class => 'form-horizontal', :method => :post do %>
  <div class="form-group">
    <label for="tableDD" class="col-sm-2 control-label">Table</label>
    <div class="col-sm-3">
      <select class="form-control" name="table_id" id="tableDD" required>
        <% @tables.each do |table| %>
            <option value="<%= table.id %>" <% if params[:table_id] == table.id.to_s %>selected<% end %>><%= table.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class='form-group'>
    <label for='dateInput' class='col-sm-2 control-label'>Date</label>
    <div class='col-sm-3'>
      <input type='date' name="date" class="form-control" id="dateInput" placeholder="date" required>
    </div>
  </div>
  <div class="form-group">
    <label for="startTimeInput" class="col-sm-2 control-label">Start time</label>
    <div class="col-sm-3">
      <input type="time" name="start_time" class="form-control" id="startTimeInput" required>
    </div>
  </div>
    <div class="form-group">
      <label for="endTimeInput" class="col-sm-2 control-label">End time</label>
      <div class="col-sm-3">
        <input type="time" name="end_time" class="form-control" id="endTimeInput" required>
      </div>
    </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-3">
      <button type="submit" class="btn btn-primary">Reserve</button>
    </div>
  </div>
<% end %>

app/views/signup/index.html.erb
<h1>Signup form</h1>
<%= form_tag('/signup', :method => "POST", :class => "form") do %>
  <div class="input-group">
    <input type="text" class="form-control" placeholder="login" name="username" autofocus="true" required>
    <input type="password" class='form-control' placeholder="password" name="password" required>
    <input type="password" class="form-control" placeholder="Confirm password" name="passwordConfirmation" required>
    <button type="submit" class="btn btn-success">Sign Up</button>
  </div>
<% end %>

app/views/tables/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Table name</th>
      <th>Description</th>
      <th>Links</th>
    </tr>
  </thead>
  <tbody>
    <% @tables.each do |table| %>
      <tr scope="row">
        <th><%= table.id %></th>
        <td><%= table.name %></td>
        <td><%= table.description %></td>
        <td><% if session[:user_id] %><%= link_to 'Reserve', new_reservation_path + '?table_id=' + table.id.to_s %><% else %>"You should be logged in to reserve a table"<% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>